MONITOR:
  BCH:
    threshold: 20.0
  BTC:
    threshold: 25.0
  DEFAULT:
    threshold: 10
  EOS:
    threshold: 20.0
  ETH:
    threshold: 25.0
  LTC:
    threshold: 25.0
  TRX:
    threshold: 25.0
  XRP:
    threshold: 20.0
